export const ROLES = Object.freeze({
  SUPER_ADMIN:     'SUPER_ADMIN',
  ADMIN_SOPORTE:   'ADMIN_SOPORTE',
  ADMIN_COMERCIAL: 'ADMIN_COMERCIAL',
  MODERADOR:       'MODERADOR',
  PROPIETARIO:     'PROPIETARIO',
  ADMINISTRADOR:   'ADMINISTRADOR',
  VENDEDOR:        'VENDEDOR',
  BODEGA:          'BODEGA',
  CAJERO:          'CAJERO',
  REPARTIDOR:      'REPARTIDOR',
  CLIENTE:         'CLIENTE',
  MECANICO:        'MECANICO',
  TALLER:          'TALLER',
  EMPRESA:         'EMPRESA',
});

export const PLATFORM_ROLES = [
  ROLES.SUPER_ADMIN, ROLES.ADMIN_SOPORTE, ROLES.ADMIN_COMERCIAL, ROLES.MODERADOR,
];

export const STORE_ROLES = [
  ROLES.PROPIETARIO, ROLES.ADMINISTRADOR, ROLES.VENDEDOR,
  ROLES.BODEGA, ROLES.CAJERO, ROLES.REPARTIDOR,
];

export const CLIENT_ROLES = [
  ROLES.CLIENTE, ROLES.MECANICO, ROLES.TALLER, ROLES.EMPRESA,
];
